# Generated by Django 5.1.6 on 2025-03-01 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('posts', '0002_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date when the event occurred', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_name',
            field=models.CharField(blank=True, help_text='Name of the event if applicable', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If private, only organization members can view'),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, help_text='Where the photo was taken', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organizations.university'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('university__isnull', True), ('company__isnull', True)), models.Q(('university__isnull', False), ('company__isnull', True)), models.Q(('university__isnull', True), ('company__isnull', False)), _connector='OR'), name='post_must_have_zero_or_one_organization'),
        ),
    ]
