# Generated by Django 5.1.6 on 2025-03-06 20:49

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_company_created_at_alter_company_industry_and_more'),
        ('posts', '0004_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Comment content (min 3 characters)', validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Content of the post (min 10 characters)', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when the event occurred', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_name',
            field=models.CharField(blank=True, db_index=True, help_text='Name of the event if applicable', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the post (optional)', null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='If private, only organization members can view'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, db_index=True, help_text='Where the photo was taken', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, help_text='Title of the post (3-255 characters)', max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='posts_comme_created_f825cb_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'author'], name='posts_comme_post_id_2be251_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'created_at'], name='posts_follo_followe_bb9837_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed', 'created_at'], name='posts_follo_followe_a1d892_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', 'created_at'], name='posts_like_post_id_425a42_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'created_at'], name='posts_like_user_id_f3340b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at', 'author'], name='posts_post_created_4a9f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_private', 'university'], name='posts_post_is_priv_755773_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_private', 'company'], name='posts_post_is_priv_423e45_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['location', 'event_date'], name='posts_post_locatio_9502b6_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['post', 'created_at'], name='posts_share_post_id_9f6264_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['user', 'created_at'], name='posts_share_user_id_8cce47_idx'),
        ),
    ]
