# Generated by Django 5.1.6 on 2025-03-10 22:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_content_alter_comment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, default=0.0, help_text='Relevance score for ranking')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('viewed', models.BooleanField(default=False)),
                ('interacted', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_appearances', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'score'], name='posts_feede_user_id_a229be_idx'), models.Index(fields=['user', 'created_at'], name='posts_feede_user_id_9c6b8e_idx'), models.Index(fields=['user', 'viewed'], name='posts_feede_user_id_af386b_idx'), models.Index(fields=['user', 'interacted'], name='posts_feede_user_id_0ebe4c_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
