# Generated by Django 5.1.6 on 2025-03-10 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_feedentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityPostCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_posts', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_cache', to='posts.post')),
            ],
            options={
                'indexes': [models.Index(fields=['author'], name='posts_celeb_author__d2eb85_idx'), models.Index(fields=['post'], name='posts_celeb_post_id_38d63d_idx'), models.Index(fields=['created_at'], name='posts_celeb_created_b531f1_idx')],
                'unique_together': {('author', 'post')},
            },
        ),
    ]
