# Generated by Django 5.1.6 on 2025-03-06 20:49

import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='If private, only invited members can access'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='joined_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='If private, only invited members can access'),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='organizatio_industr_3c89e1_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name', 'university'], name='organizatio_name_88c190_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email', 'status'], name='organizatio_email_b06ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['created_at'], name='organizatio_created_d72627_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['expires_at'], name='organizatio_expires_fb3b75_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'university'], name='organizatio_user_id_91d14d_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'company'], name='organizatio_user_id_a6c30d_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['joined_at'], name='organizatio_joined__de2446_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['location'], name='organizatio_locatio_522aa1_idx'),
        ),
    ]
