# Generated by Django 5.1.6 on 2025-03-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_company_created_at_alter_company_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether invitation email was sent'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='last_email_attempt',
            field=models.DateTimeField(blank=True, help_text='When the last email attempt was made', null=True),
        ),
    ]
